---
title: "My English Activity Log : MEAL"
author:
  - name: "Nathanaël Cossez" 
date: "`r Sys.Date()`"
categories:
  - "English for Science"
  
output: distill::distill_article
---


- Sept. 29th: I've started reading/watching the news on the BBC new's app.

- Oct. 8th: I watched 1 episode of "deadly class" on netflix(English with English subtitles). A little bit bloody.

- Oct. 15th: I played video games (the witcher 3) in english.

- Oct. 21th: I spoke with my girlfriend in english for a day.

- Oct. 25th: I watched an other episode of "deadly class", i like this series.

- Nov. 4th: I sang somme song in english with the lyrics, (eg: bohemian rhapsody, can't help falling in love, etc) and learn the english version of music note.

- Nov. 4th: I listened to all the repertory of the bittles band.

- Dec. 10th to feb. 1st: I studied and passed my exams.

- feb. 5th: I read the treasure island in EnglishI read the treasure island in English

- feb. 10th: I chatted on an english music forum about making beats from scratch

- feb. 15th: I tried to write a song in english. It's a fail.

- feb. 25th: I watched an anime in VO with english subtitle. The anime is "sky high survival"

- mar. 3th : I listened the last album of Ed Sheeran and tried to understand all the lyrics.
